on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'xtask/**'
      - Cargo.toml
      - README.md
      - update.sh
      - .github/workflows/update.yml
      - .github/workflows/populate-rust-analyzer-cache.yml

  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'xtask/**'
      - Cargo.toml
      - README.md
      - update.sh
      - .github/workflows/update.yml
      - .github/workflows/populate-rust-analyzer-cache.yml

  workflow_dispatch:

name: Build nix packages
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Install Nix
      uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enable cachix
      uses: cachix/cachix-action@6e4751ed42b22f60165d3f266cfa4cce66ae406d
      with:
        name: msfjarvis
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Enable cachix binary cache
      run: cachix use msfjarvis

    - name: Build Nix packages
      run: |
        # Compile all packages
        nix-build
        # Compile again, but since it's already cached we simply get a list of store paths
        # that can be pushed to cachix.
        nix-build | cachix push msfjarvis -c9
