on:
  push:
    branches:
      - develop

  pull_request:

name: Check nix packages
jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Install Nix
      uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enable cachix
      uses: cachix/cachix-action@6e4751ed42b22f60165d3f266cfa4cce66ae406d
      if: "${{ github.event_name == 'push' }}"
      with:
        name: msfjarvis
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Enable cachix binary cache
      run: cachix use msfjarvis

    - name: Build Nix packages
      if: "${{ github.event_name == 'pull_request' }}"
      run: nix-build

    - name: Stream to cachix
      if: "${{ github.event_name == 'push' }}"
      run: nix-build | cachix push msfjarvis
